# Natural Language Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle


## Importing the dataset

In [3]:
# dataset = pd.read_csv('amazon_unlocked_mobile_datasets_with_sentiment.csv')
# df = pd.DataFrame(dataset, columns=['Device', 'Company', 
#                                  'Reviews',
#                                  'Result'])

# Postive_df = df[~df['Result'].isin(['negative','neutral'])]
# Positive=Postive_df.drop(Postive_df.index[6397:])
# Positive.to_csv('Postive_Review.csv', index=False)
# Postivedf = pd.DataFrame(Positive, columns=['Device', 'Company', 
#                                  'Reviews',
#                                  'Result'])

# Negative_df = df[~df['Result'].isin(['positive','neutral'])]
# Negative=Negative_df.drop(Negative_df.index[6397:])
# Negative.to_csv('Negative_Review.csv', index=False)
# Negativedf = pd.DataFrame(Negative, columns=['Device', 'Company', 
#                                  'Reviews',
#                                  'Result'])

# Neutral_df = df[~df['Result'].isin(['positive','negative'])]
# Neutral=Neutral_df.drop(Neutral_df.index[6397:])
# Neutral_df.to_csv('Neutral_Review.csv', index=False)
# Neutraldf = pd.DataFrame(Neutral_df, columns=['Device', 'Company', 
#                                  'Reviews',
#                                  'Result'])

# PostiveDS=pd.read_csv("Postive_Review.csv")
# NegativeDS=pd.read_csv("Negative_Review.csv")
# NeutralDS=pd.read_csv("Neutral_Review.csv")
# Final_df =pd.merge(PostiveDS, NegativeDS, how='outer')
# Final_df.to_csv('FinalDataset.csv', index=False)
# Final_DF=pd.read_csv("FinalDataset.csv")
# Finaldf =pd.merge(Final_DF, NeutralDS, how='outer')
# #Finaldf.to_csv('Final_Dataset.csv', index=False)
Final_Df=pd.read_csv("Final_Dataset.csv")



In [4]:
print(Final_Df)


                                                  Device     Company   
0      "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     Samsung  \
1      "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     Samsung   
2      "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     Samsung   
3      "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     Samsung   
4      "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     Samsung   
...                                                  ...         ...   
19186  BlackBerry Storm 2 9550 Unlocked Phone - No Wa...  BlackBerry   
19187  BlackBerry Storm 2 9550 Unlocked Phone - No Wa...  BlackBerry   
19188  BlackBerry Storm 2 9550 Unlocked Phone - No Wa...  BlackBerry   
19189  BlackBerry Storm 2 9550 Unlocked Phone - No Wa...  BlackBerry   
19190  BlackBerry Storm 2 9550 Unlocked Phone - No Wa...  BlackBerry   

                                                 Reviews    Result  
0      I feel so LUCKY to have found this used (phone...  positive

## Cleaning the texts

In [5]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 19191):
  review = re.sub('[^a-zA-Z]', ' ', Final_Df['Reviews'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
print(corpus)

['feel lucki found use phone us not use hard phone line someon upgrad sold one son like old one final fell apart year want upgrad thank seller realli appreci honesti said use phone recommend seller highli would', 'nice phone nice grade pantach revu clean set easi set never android phone fantast say least perfect size surf social media great phone samsung', 'pleas', 'work good goe slow sometim good phone love', 'great phone replac lost phone thing volum button not work still go set adjust job elig upgrad phone thaank', 'phone look good stay charg buy new batteri still stay charg long trash money lost never buy person', 'origin use samsung galaxi sprint want return back samsung epic g sprint realli miss keyboard realli like smaller compact size phone still need basic function smart phone e check e mail get direct text messag phone not power newer cell phone awar applic instal slower phone run like freez time time camera work great video great well even web brows decent give need also not

## Creating the Bag of Words model

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 19191)
X = cv.fit_transform(corpus).toarray()
y = Final_Df.iloc[:, -1].values

In [7]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [8]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(X)

[[ 1  3  0]
 [ 0  3  0]
 [ 0  0  0]
 [ 0  1  1]
 [ 1  3  1]
 [ 0  1  0]
 [ 1  6  1]
 [ 0  0  0]
 [ 0  1  0]
 [ 0  1  0]
 [ 0  0  0]
 [ 2  3  0]
 [ 0  4  0]
 [ 0  2  0]
 [ 0  3  1]
 [ 1  2  0]
 [ 0  0  0]
 [ 0  3  0]
 [ 0  3  0]
 [ 0  1  0]
 [ 0  0  0]
 [ 0  1  1]
 [ 1  1  0]
 [ 0  0  0]
 [ 0  2  0]
 [ 0  1  0]
 [ 0  2  0]
 [ 0  0  0]
 [ 0  1  0]
 [ 0  1  0]
 [ 0  1  0]
 [ 0  0  1]
 [ 0  8  0]
 [ 0  4  1]
 [ 0  1  0]
 [ 1  2  2]
 [ 0  1  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 1 10  1]
 [ 0  2  0]
 [ 4  5  2]
 [ 0  1  0]
 [ 0  1  0]
 [ 0  1  0]
 [ 1  2  0]
 [ 1  4  1]
 [ 0  2  0]
 [ 1  1  0]
 [ 1  0  0]
 [ 0  3  0]
 [ 0  1  0]
 [ 3  9  3]
 [ 0  0  0]
 [ 0  1  0]
 [ 0  1  1]
 [ 1  0  1]
 [ 0  2  0]
 [ 0  2  1]
 [ 0  1  0]
 [ 0  1  0]
 [ 1  0  0]
 [ 0  1  0]
 [ 2  5  0]
 [ 0  1  1]
 [ 4 25  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  3  0]
 [ 0  0  0]
 [ 0  1  0]
 [ 0  0  0]
 [ 0  4  1]
 [ 0  0  0]
 [ 3  3  1]
 [ 1  5  0]
 [ 0  1  0]
 [ 0  0  0]
 [ 1  3  0]
 [ 0  1  0]
 [ 1  2  0]
 [ 2

In [11]:
print(y)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [12]:
# Oversample and plot imbalanced dataset with SMOTE
from collections import Counter
from sklearn.datasets import make_classification

from matplotlib import pyplot
from numpy import where
# define dataset

# summarize class distribution
counter = Counter(y)
print(counter)
# transform the dataset
# oversample = SMOTE()
# X, y = oversample.fit_resample(X, y)
# # summarize the new class distribution
# counter = Counter(y)
# print(counter)
# # scatter plot of examples by class label
# for label, _ in counter.items():
# 	row_ix = where(y == label)[0]
# 	pyplot.scatter(X[row_ix, 0], X[row_ix, 1], label=str(label))
# pyplot.legend()
# pyplot.show()

Counter({2: 109, 0: 41, 1: 31})


## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 42)



## Training the Logistic Regression model on the Training set

In [14]:
# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression(random_state = 0)
# classifier.fit(X_train, y_train)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier


log_clf = LogisticRegression(max_iter=1000,random_state=0)
dt_clf = DecisionTreeClassifier(random_state=0)
svm_clf = SVC(gamma="auto",probability=True, random_state=0)

#soft voting
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('dt', dt_clf), ('svc', svm_clf)],
    voting='soft')
voting_clf.fit(X_train, y_train)
for clf in (log_clf, dt_clf, svm_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test, y_pred))
vocabulary = cv.vocabulary_    
print(vocabulary)

0.9261896491837444
0.9103855505383813
0.5208405696422369
0.9322681486627301
{'feel': 2349, 'lucki': 3807, 'found': 2506, 'use': 6904, 'phone': 4679, 'us': 6891, 'not': 4301, 'hard': 2898, 'line': 3713, 'someon': 5910, 'upgrad': 6875, 'sold': 5897, 'one': 4407, 'son': 5918, 'like': 3704, 'old': 4398, 'final': 2390, 'fell': 2351, 'apart': 317, 'year': 7309, 'want': 7059, 'thank': 6420, 'seller': 5603, 'realli': 5131, 'appreci': 343, 'honesti': 3038, 'said': 5471, 'recommend': 5179, 'highli': 2996, 'would': 7262, 'nice': 4250, 'grade': 2767, 'pantach': 4555, 'revu': 5377, 'clean': 1191, 'set': 5639, 'easi': 2002, 'never': 4229, 'android': 269, 'fantast': 2314, 'say': 5504, 'least': 3636, 'perfect': 4636, 'size': 5787, 'surf': 6239, 'social': 5891, 'media': 3927, 'great': 2792, 'samsung': 5483, 'pleas': 4753, 'work': 7231, 'good': 2731, 'goe': 2721, 'slow': 5838, 'sometim': 5914, 'love': 3793, 'replac': 5296, 'lost': 3784, 'thing': 6458, 'volum': 7023, 'button': 930, 'still': 6099, 'go': 2

In [11]:
with open('vocabulary.pkl', 'wb') as file:
    pickle.dump(vocabulary, file)

## Training the Decision Tree Classification model on the Training set


## Predicting the Test set results

In [16]:
y_pred = clf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [2 1]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 0]
 [2 0]
 [2 2]
 [2 1]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [1 2]
 [2 0]
 [2 0]
 [2 2]
 [2 2]
 [2 1]
 [0 2]
 [2 2]
 [2 0]
 [2 1]
 [2 0]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 0]
 [2 2]
 [2 2]
 [0 2]
 [2 2]
 [2 2]
 [1 0]
 [2 2]
 [2 1]
 [0 0]
 [0 2]
 [2 2]
 [2 1]
 [1 0]
 [2 1]
 [2 1]
 [2 2]
 [1 1]
 [2 2]]


In [13]:

import re

new_reviews = [
    input("Enter a new review: "),
  
]
# B = np.reshape(Review, (-1, 2))
new_X = cv.transform(new_reviews).toarray()

result=voting_clf.predict(new_X)
print(result)

[0]


## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1761   72   93]
 [  55 1869   11]
 [ 112   47 1738]]


0.9322681486627301

In [15]:
pickle.dump(voting_clf, open("model.pkl", "wb"))